name: MacOS-latest

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: bootstrap script
      run: sh scripts/bootstrap.sh
    - name: execute tests
      run: sh scripts/test_macos.sh